name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: NPM pre-config
      run: |
        npm install
        npm install -D @vuepress/plugin-back-to-top
        npm install -D @vuepress/plugin-medium-zoom
      
    - name: Build
      run: npm run build
      
    - name: setup git config
      run: |
        # setup the username and email. 
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<>"
          
    - name: add and commit
      run: |
        cd src/.vuepress/dist
        echo 'docs.play-mc.fr' > CNAME
        git init
        git add -A
        git commit -m 'deploy'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./src/.vuepress/dist

