# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: NPM pre-config
      run: npm install
      
    - name: Build
      run: npm run build
      
   # - run: git config --global user.name "Robot"
   # - run: git config --global user.email contact@play-mc.fr

   # - run: cd src/.vuepress/dist && echo 'docs.play-mc.fr' > CNAME
   # - run: cd src/.vuepress/dist && git init
   # - run: cd src/.vuepress/dist && git add -A
   # - run: cd src/.vuepress/dist && git commit -m 'deploy'

    - name: setup git config
      run: |
        # setup the username and email. 
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
          
    - name: add and commit
      run: |
        cd src/.vuepress/dist
        echo 'docs.play-mc.fr' > CNAME
        git init
        git add -A
        git commit -m 'deploy'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./src/.vuepress/dist

